version: "3.7"

services:
  web:
    platform: linux/amd64
    container_name: spring-reddi-server
    image: 533267191976.dkr.ecr.ap-northeast-2.amazonaws.com/reddi-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"