version: "3.7"

services:
  web:
    platform: linux/amd64
    container_name: spring-reddi-server
    image: reddi-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env.dev
    volumes:
      - ./:/app