version: "3.7"

services:
  web:
#    platform: linux/amd64
    container_name: spring-reddi-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env.dev
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379"