---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env.local[.properties]
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  jpa:
    hibernate:
      ddl-auto: create # 추후 수정
---

# default 공통 설정
spring:
  profiles:
    active: local # default 프로파일 : local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile, email
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui # html 문서 접속 경로
  paths-to-match:
    - /**
  cache:
    disabled: true

notion:
  api:
    key: ${NOTION_API_KEY}
  brandDB:
    id: ${NOTION_BRAND_DB_ID}
  marketingDB:
    id: ${NOTION_MARKETING_DB_ID}


